---
title: "Econometric Methods "
subtitle: "School of Economics, Quaid-i-Azam University, Islamabad"
format: pdf
---

**Encricle/Cross the correct answer.**


1) The binary dependent variable model is an example of a:
A) regression model, which has as a regressor, among others, a binary variable.
B) model that cannot be estimated by OLS.
C) limited dependent variable model. 
D) model where the left-hand variable is measured in base 2.
2) The following are examples of limited dependent variables, with the exception of:
A) binary dependent variable.
B) log-log specification.
C) truncated regression model.
D) discrete choice model.
3) In the binary dependent variable model, a predicted value of 0.6 means that:
A) the most likely value the dependent variable will take on is 60 percent. 
B) given the values for the explanatory variables, there is a 60 percent probability that the dependent variable will equal one.
C) the model makes little sense, since the dependent variable can only be 0 or 1.
D) given the values for the explanatory variables, there is a 40 percent probability that the dependent variable will equal one.

4) $E(Y  X1,..., Xk) = Pr(Y = 1  X1,..., Xk)$ means that:
A) for a binary variable model, the predicted value from the population regression is the probability that Y=1, given X.
B) dividing Y by the X's is the same as the probability of Y being the inverse of the sum of the X's.
C) the exponential of Y is the same as the probability of Y happening.
D) you are pretty certain that Y takes on a value of 1 given the X's.
5) The linear probability model is:
A) the application of the multiple regression model with a continuous left-hand side variable and a binary variable as at least one of the regressors.
B) an example of  probit estimation.
C) another word for logit estimation.
D) the application of the linear multiple regression model to a binary dependent variable.
 
6) In the linear probability model, the interpretation of the slope coefficient is:
A) the change in odds associated with a unit change in X, holding other regressors constant.
B) not all that meaningful since the dependent variable is either 0 or 1. 
C) the change in probability that Y=1 associated with a unit change in X, holding others regressors constant.
D) the response in the dependent variable to a percentage change in the regressor.
7) The following tools from multiple regression analysis carry over in a meaningful manner to the linear probability model, with the exception of the:
A) F-statistic.
B) significance test using the t-statistic.
C) 95% confidence interval using ± 1.96 times the standard error.
D) regression R2.
8) The following are reasons for studying randomized controlled experiment in an econometrics course, with the exception of:
A) at a conceptual level, the notion of an ideal randomized controlled experiment provides a benchmark against which to judge estimates of causal effects in practice.
B) when experiments are actually conducted, their results can be very influential, so it is important to understand the limitations and threats to validity of actual experiments as well as their strength.
C) randomized controlled experiments in economics are common.
D) external circumstances sometimes produce what appears to be randomization.
9) Program evaluation:
A) is conducted for most departments in your university/college about every seven years.
B) is the field of study that concerns estimating the effect of a program, policy, or some other intervention or "treatment."
C) tries to establish whether EViews, SAS or Stata work best for your econometrics course.
D) establishes rating systems for television programs in a controlled experiment framework.
10) In the context of a controlled experiment, consider the simple linear regression formulation $Y_i = \beta_0 + \beta_0 X_i + u_i$. Let the $Y_i$ be the outcome, $X_i$ the treatment level, and $u_i$ contain all the additional determinants of the outcome. Then:
A) the OLS estimator of the slope will be inconsistent in the case of a randomly assigned Xi since there are omitted variables present.
B) $X_i$ and ui will be independently distributed if the $X_i$ be are randomly assigned.
C) $\beta_0$ represents the causal effect of $X$ on $Y$ when $X$ is zero.
D) $E(Y/X = 0)$is the expected value for the treatment group.

11) In the context of a controlled experiment, consider the simple linear regression formulation $Y_i = \beta_0 + \beta_1 X_i + u_i$. Let the $Y_i$ be the outcome, $X_i$ the treatment level when the treatment is binary, and $u_i$ contain all the additional determinants of the outcome. Then calling   a differences estimator:
12) makes sense since it is the difference between the sample average outcome of the treatment group and the sample average outcome of the control group.
B) and    the level estimator is standard terminology in randomized controlled experiments.
C) does not make sense, since neither $Y$ nor $X$ are in differences.
D) is not quite accurate since it is actually the derivative of $Y$ on $X$.
13) The following does not represent a threat to internal validity of randomized controlled experiments:
A) attrition.
B) failure to follow the treatment protocol.
C) experimental effects.
D) a large sample size.

14) Estimation of the IV regression model:
A) requires exact identification.
B) allows only one endogenous regressor, which is typically correlated with the error term.
C) requires exact identification or overidentification.
D) is only possible if the number of instruments is the same as the number of regressors.
15) Two Stage Least Squares is calculated as follows; in the first stage:
A) Y is regressed on the exogenous variables only. The predicted value of Y is then regressed on the instrumental variables.
B) the unknown coefficients in the reduced form equation are estimated by OLS, and the predicted values are calculated. In the second stage, Y is regressed on these predicted values and the other exogenous variables.
C) the exogenous variables are regressed on the instruments. The predicted value of the exogenous variables is then used in the second stage, together with the instruments, to predict the dependent variable.
D) the unknown coefficients in the reduced form equation are estimated by weighted least squares, and the predicted values are calculated. In the second stage, Y is regressed on these predicted values and the other exogenous variables.
16) The conditions for a valid instruments do not include the following: 
A) each instrument must be uncorrelated with the error term.
B) each one of the instrumental variables must be normally distributed.
C) at least one of the instruments must enter the population regression of X on the Zs and the Ws.
D) perfect multicollinearity between the predicted endogenous variables and the exogenous variables must be ruled out.
17) The IV regression assumptions include all of the following with the exception of:
A) the error terms must be normally distributed.
B) $E(u_i/ W_{1i},…, W_{ri}) = 0$.
C) Large outliers are unlikely: the $X's$, $W's$, $Z's$, and $Y's$ all have nonzero, finite fourth moments.
D) $(X1i,…, Xki, W1i,…,Wri, Z1i, … Zmi, Yi)$ are i.i.d. draws from their joint distribution.
18) The rule-of-thumb for checking for weak instruments is as follows: for the case of a single endogenous regressor:
A) a first stage F must be statistically significant to indicate a strong instrument.
B) a first stage F > 1.96 indicates that the instruments are weak.
C) the t-statistic on each of the instruments must exceed at least 1.64.
D) a first stage F < 10 indicates that the instruments are weak.
19) The J-statistic:
A) tells you if the instruments are exogenous.
B) provides you with a test of the hypothesis that the instruments are exogenous for the case of exact identification.
C) is distributed   where m-k is the degree of overidentification.
D) is distributed   where m-k is the number of instruments minus the number of regressors.
20) In the case of the simple regression model $Y_i = \beta_0 + \beta_1X_i + u_i$, $i = 1,…, n$, when $X$ and $u$ are correlated, then:
A) the OLS estimator is biased in small samples only.
B) OLS and TSLS produce the same estimate.
C) $X$ is exogenous.
D) the OLS estimator is inconsistent.



# Part 2

## 1. 

Imagine that we are interested in analyzing a government program. We consider individuals as *treated* if they participated in the program (and untreated if they did not). Following the notation of the Rubin causal model, imagine that we observe the following sample (which would be impossible observe in real life):

```{r, echo = F, warning = F, message = F, error = F}
rubin_df = data.frame(
  i = 1:6,
  trt = c(0,0,0,1,1,1),
  y1 = c(2, 3, 1, 9, 0, 6),
  y0 = c(4, 5, 3, 5, 0, 4)
)
```

-   1a.Calculate and report the treatment effect **for each individual** (*i.e.*, $\tau_i$).

-   1b.**Within the control group:** Is the treatment effect heterogeneous or homogeneous? Briefly explain your answer.

-   1c. **Across the treatment group and control group** (for both groups, jointly):\] Is the treatment effect heterogeneous or homogeneous? Briefly explain your answer.

-   1d. Calculate and interpret the **average treatment effect** for the sample.

-   1e. What does it mean if $\tau_i < 0$ for one individual and $\tau_j > 0$ for another individual?

-   1f. Define and explain selection bias.

## Instrumental Variables

-   1g. What are three requirements for a valid instrumental variable? Explain each requirement.

-   1h. What is the difference between an endogenous variable and an exogenous variable?

-   1i. Suppose your boss wants you to estimate the effect of whether counties have COVID-related shutdowns on the counties' infection rates (infections per 10,000), *i.e.*,


$$
\text{Infection rate}_i = \beta_0 + \beta_1 (\text{Has shutdown})_i + u_i
$$


Should you be concerned with endogeneity in this regression? Explain your answer.

-   1j. Now your boss suggests using whether the county's (state's) governor is a Democrat as an instrument. In other words: The proposed instrumental variable is an indicator for whether the governor is a Democract for the state that contains county $i$. Is this a valid instrument? Explain using both of the requirements for a valid instrument.

## 2.

a)	Describe the consequences of estimating an equation by OLS in the presence of an endogenous regressor. How can you overcome these obstacles? Present an alternative estimator and state its properties. 

b)	Consider the following probit regression

	Pr(Y = 1  X) = Φ(8.9 – 0.14 × X)

Calculate the change in probability for X increasing by 10 for X = 40 and X = 60. Why is there such a large difference in the change in probabilities?

